# Generated by Django 4.1 on 2022-09-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafoglio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodo_pagamento_carta',
            name='carta_codice',
            field=models.CharField(max_length=20),
        ),
    ]
