# Generated by Django 4.1 on 2022-08-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafoglio', '0002_alter_metodo_pagamento_paypal_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='metodo_pagamento_paypal',
        ),
    ]
