# Generated by Django 4.1 on 2022-08-16 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profilo', '0003_alter_profilo_immagine_profilo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine_copertina', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('nome', models.CharField(max_length=50)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stato_articolo', models.CharField(choices=[('nu', 'nuovo'), ('pr', 'come nuovo'), ('us', 'usato'), ('re', 'ricondizionato')], max_length=2)),
                ('descrizione', models.CharField(max_length=1000)),
                ('profilo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profilo.profilo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Prodotti',
            },
        ),
    ]
