# Generated by Django 4.1 on 2022-09-04 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portafoglio', '0001_initial'),
        ('profilo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine_copertina', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('nome', models.CharField(max_length=50)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stato_articolo', models.CharField(choices=[('nu', 'nuovo'), ('pr', 'come nuovo'), ('us', 'usato'), ('re', 'ricondizionato')], max_length=2)),
                ('descrizione', models.CharField(max_length=1000)),
                ('disponibilita', models.BooleanField(default='True')),
                ('categoria', models.CharField(choices=[('info', 'informatica'), ('phone', 'telefonia'), ('games', 'console e giochi'), ('book', 'Libri'), ('model', 'modellini')], max_length=5)),
                ('profilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilo.profilo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Prodotti',
            },
        ),
        migrations.CreateModel(
            name='Prodotto_ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dop', models.DateTimeField(default=django.utils.timezone.now)),
                ('indirizzo', models.CharField(max_length=100)),
                ('stato', models.IntegerField(default=1)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafoglio.metodo_pagamento_carta')),
                ('prodotto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.prodotto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prdotto_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.prodotto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
