# Generated by Django 4.1 on 2022-08-16 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilo', '0003_alter_profilo_immagine_profilo'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='profilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilo.profilo'),
        ),
    ]
