# Generated by Django 4.1 on 2022-08-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_prodotto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='disponibilita',
            field=models.BooleanField(default='True'),
        ),
    ]
