# Generated by Django 4.1 on 2022-08-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_prodotto_disponibilita'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='categoria',
            field=models.CharField(choices=[('info', 'informatica'), ('phone', 'telefonia'), ('games', 'console e giochi'), ('book', 'Libri'), ('model', 'modellini')], default='book', max_length=5),
        ),
    ]
