# Generated by Django 4.1 on 2022-08-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_prodotto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='stato_articolo',
            field=models.CharField(choices=[('1', 'in sviluppo'), ('2', 'spedito'), ('3', 'consegnato')], max_length=2),
        ),
    ]
