# Generated by Django 4.1 on 2022-08-18 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portafoglio', '0003_delete_metodo_pagamento_paypal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0007_alter_prodotto_stato_articolo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotto_ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indirizzo', models.CharField(max_length=100)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafoglio.metodo_pagamento_carta')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.prodotto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
