# Generated by Django 4.1 on 2022-08-18 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_prodotto_ordine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto_ordine',
            name='prodotto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.prodotto'),
        ),
    ]
