# Generated by Django 4.1 on 2022-08-30 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0010_prodotto_ordine_dop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='stato_articolo',
            field=models.CharField(choices=[('nu', 'nuovo'), ('pr', 'come nuovo'), ('us', 'usato'), ('re', 'ricondizionato')], max_length=2),
        ),
        migrations.CreateModel(
            name='Prdotto_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.prodotto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
