# Generated by Django 4.1 on 2022-09-02 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0012_prodotto_recensione'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto_ordine',
            name='stato',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Prodotto_segnalazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dop', models.DateTimeField(default=django.utils.timezone.now)),
                ('descrizione', models.CharField(max_length=1000)),
                ('prova_immagine_1', models.ImageField(null=True, upload_to='segnalazioni/')),
                ('prova_immagine_2', models.ImageField(blank=True, null=True, upload_to='segnalazioni/')),
                ('prova_immagine_3', models.ImageField(blank=True, null=True, upload_to='segnalazioni/')),
                ('ordine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.prodotto_ordine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
