# Generated by Django 4.1 on 2022-09-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_prodotto_ordine_stato_prodotto_segnalazione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodotto_segnalazione',
            name='ordine',
        ),
        migrations.RemoveField(
            model_name='prodotto_segnalazione',
            name='user',
        ),
        migrations.DeleteModel(
            name='Prodotto_recensione',
        ),
        migrations.DeleteModel(
            name='Prodotto_segnalazione',
        ),
    ]
