# Generated by Django 4.1 on 2022-09-04 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine_profilo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('regione', models.CharField(choices=[('1', 'EMILIA-ROMAGNA'), ('2', 'VENETO'), ('3', 'LOMBARDIA'), ('4', 'PIEMONTE')], default=1, max_length=20)),
                ('cap', models.DecimalField(decimal_places=0, max_digits=5)),
                ('citta', models.CharField(max_length=50)),
                ('indirizzo', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profili',
            },
        ),
    ]
