# Generated by Django 4.1 on 2022-08-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilo',
            name='immagine_profilo',
            field=models.ImageField(null=True, upload_to='image/profilo/'),
        ),
    ]
