# Generated by Django 4.1 on 2022-09-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilo',
            name='cap',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='profilo',
            name='regione',
            field=models.CharField(choices=[('1', 'EMILIA-ROMAGNA'), ('2', 'VENETO'), ('3', 'LOMBARDIA'), ('4', 'PIEMONTE')], default=1, max_length=20),
        ),
    ]
