# Generated by Django 4.1 on 2022-08-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilo', '0002_alter_profilo_immagine_profilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilo',
            name='immagine_profilo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
