# Generated by Django 4.1 on 2022-09-02 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0014_remove_prodotto_segnalazione_ordine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='segnalazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dop', models.DateTimeField(default=django.utils.timezone.now)),
                ('descrizione', models.CharField(max_length=1000)),
                ('prova_immagine_1', models.ImageField(null=True, upload_to='segnalazioni/')),
                ('prova_immagine_2', models.ImageField(blank=True, null=True, upload_to='segnalazioni/')),
                ('prova_immagine_3', models.ImageField(blank=True, null=True, upload_to='segnalazioni/')),
                ('ordine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.prodotto_ordine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dop', models.DateTimeField(default=django.utils.timezone.now)),
                ('voto', models.DecimalField(choices=[('1', 'pessimo'), ('2', 'discreto'), ('3', 'buono'), ('4', 'molto buono'), ('5', 'perfetto')], decimal_places=1, max_digits=3)),
                ('descrizione', models.CharField(max_length=1000)),
                ('ordine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.prodotto_ordine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messaggi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('img', models.ImageField(blank=True, upload_to='chat/')),
                ('dop', models.DateTimeField(default=django.utils.timezone.now)),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.prodotto')),
                ('user_invio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invio', to=settings.AUTH_USER_MODEL)),
                ('user_ricevi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ricevi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
