# Generated by Django 4.1 on 2022-09-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaggi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messaggi',
            name='message',
            field=models.CharField(max_length=5000),
        ),
    ]
