# Generated by Django 4.1 on 2022-09-02 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_prodotto_segnalazione_ordine_and_more'),
        ('messaggi', '0002_alter_messaggi_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messaggi',
            name='prodotto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.prodotto'),
        ),
    ]
